export const FETCH_GAMES_LOADING: string = "FETCH_GAMES_LOADING";
export const FETCH_GAMES_SUCCESS: string = "FETCH_GAMES_SUCCESS";
export const FETCH_GAMES_FAILED: string = "FETCH_GAMES_FAILED";

export const FETCH_CAMPAIGNS_LOADING: string = "FETCH_CAMPAIGNS_LOADING";
export const FETCH_CAMPAIGNS_SUCCESS: string = "FETCH_CAMPAIGNS_SUCCESS";
export const FETCH_CAMPAIGNS_FAILED: string = "FETCH_CAMPAIGNS_FAILED";
export const ADD_CAMPAIGN: string = "ADD_CAMPAIGN";